# Generated by Django 5.2.5 on 2026-04-02 11:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('patient_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('body_part', models.CharField(max_length=255)),
                ('modality', models.CharField(max_length=255)),
                ('center', models.CharField(blank=True, max_length=255)),
                ('institute_name', models.CharField(blank=True, max_length=255)),
                ('scan_datetime', models.DateTimeField()),
                ('locked', models.BooleanField(default=False)),
                ('group', models.CharField(blank=True, max_length=255)),
                ('reported_by', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-scan_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Institute Name')),
                ('is_default', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CenterName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Center Name')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center_names', to='myapp.center')),
            ],
        ),
        migrations.CreateModel(
            name='DICOMImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('report_content', models.TextField(blank=True, null=True)),
                ('center_name', models.CharField(db_index=True, default='', help_text='Name of the imaging center', max_length=200)),
                ('patient_name', models.CharField(blank=True, default='', max_length=200)),
                ('patient_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('patient_birth_date', models.CharField(blank=True, max_length=8, null=True)),
                ('patient_sex', models.CharField(blank=True, default='', max_length=10)),
                ('study_instance_uid', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('study_date', models.CharField(blank=True, max_length=8, null=True)),
                ('study_time', models.CharField(blank=True, max_length=14, null=True)),
                ('study_description', models.CharField(blank=True, default='', max_length=200)),
                ('referring_physician', models.CharField(blank=True, default='', max_length=200)),
                ('series_instance_uid', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('series_number', models.CharField(blank=True, max_length=12, null=True)),
                ('series_description', models.CharField(blank=True, default='', max_length=200)),
                ('modality', models.CharField(blank=True, db_index=True, default='', max_length=16)),
                ('sop_instance_uid', models.CharField(db_index=True, max_length=64, unique=True)),
                ('instance_number', models.CharField(blank=True, max_length=12, null=True)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(default=0)),
                ('image_orientation', models.TextField(blank=True, default='')),
                ('image_position', models.TextField(blank=True, default='')),
                ('pixel_spacing', models.TextField(blank=True, default='')),
                ('slice_thickness', models.FloatField(blank=True, null=True)),
                ('assigned_doctors', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('Not Assigned', 'Not Assigned'), ('Unreported', 'Unreported'), ('Draft', 'Draft'), ('Reviewed', 'Reviewed'), ('Reported', 'Reported')], db_index=True, default='Not Assigned', max_length=20)),
                ('reported_by', models.CharField(blank=True, default='', max_length=200)),
                ('is_emergency', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dicom_images',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['center_name'], name='dicom_image_center__5b2f5c_idx'), models.Index(fields=['center_name', 'patient_id'], name='dicom_image_center__69c47f_idx'), models.Index(fields=['center_name', 'study_instance_uid'], name='dicom_image_center__2a7565_idx'), models.Index(fields=['patient_id', 'study_instance_uid'], name='dicom_image_patient_6d5a82_idx'), models.Index(fields=['study_instance_uid', 'series_instance_uid'], name='dicom_image_study_i_07d0ab_idx'), models.Index(fields=['modality', 'study_date'], name='dicom_image_modalit_60bb28_idx'), models.Index(fields=['status', 'assigned_doctors'], name='dicom_image_status_c88ae3_idx'), models.Index(fields=['created_at'], name='dicom_image_created_b6a421_idx')],
            },
        ),
        migrations.CreateModel(
            name='DoctorUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dicom_file', models.FileField(blank=True, null=True, upload_to='dicom_files/')),
                ('report_pdf', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Not Assigned', 'Not Assigned'), ('Unreported', 'Unreported'), ('Draft', 'Draft'), ('Reviewed', 'Reviewed'), ('Reported', 'Reported')], default='Not Assigned', max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='myapp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_part', models.CharField(max_length=100, verbose_name='Body Part')),
                ('template_name', models.CharField(max_length=200, verbose_name='Template Name')),
                ('content', models.TextField(verbose_name='Template Content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Template',
                'verbose_name_plural': 'Report Templates',
                'ordering': ['body_part', 'template_name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bmdc_reg_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='BMDC Reg. No')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('biometric_scan', models.FileField(blank=True, null=True, upload_to='biometrics/')),
                ('can_assign_doctors', models.BooleanField(default=False)),
                ('can_write_reports', models.BooleanField(default=False)),
                ('can_manage_templates', models.BooleanField(default=False)),
                ('can_view_images', models.BooleanField(default=False)),
                ('assigned_institutions', models.ManyToManyField(blank=True, help_text='Institutions this doctor is assigned to', related_name='assigned_doctors', to='myapp.center')),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.center')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActiveViewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_uid', models.CharField(db_index=True, max_length=64)),
                ('user_name', models.CharField(max_length=255)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'active_viewers',
                'indexes': [models.Index(fields=['study_uid', 'last_active'], name='active_view_study_u_097332_idx')],
            },
        ),
    ]
