# Generated by Django 5.2.5 on 2025-10-27 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='name',
        ),
        migrations.AddField(
            model_name='dicomimage',
            name='report_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dicomimage',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='biometric_scan',
            field=models.FileField(blank=True, null=True, upload_to='biometrics/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bmdc_reg_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='BMDC Reg. No'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AlterField(
            model_name='center',
            name='institute_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Institute Name'),
        ),
        migrations.CreateModel(
            name='CenterName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Center Name')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center_names', to='myapp.center')),
            ],
        ),
    ]
