# Generated by Django 5.2.5 on 2026-04-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='allowed_users',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
