# Generated by Django 5.2.5 on 2026-05-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_center_allowed_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomimage',
            name='patient_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dicomimage',
            name='referral_file',
            field=models.FileField(blank=True, null=True, upload_to='referrals/'),
        ),
    ]
