# Generated by Django 5.2.5 on 2026-06-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_dicomimage_patient_history_dicomimage_referral_file'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dicomimage',
            index=models.Index(fields=['patient_id', '-created_at'], name='dicom_image_patient_f3cea0_idx'),
        ),
    ]
