# Generated by Django 5.2.5 on 2026-01-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_reporttemplate_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assigned_institutions',
            field=models.ManyToManyField(blank=True, help_text='Institutions this doctor is assigned to', related_name='assigned_doctors', to='myapp.center'),
        ),
    ]
