# Generated by Django 5.2.5 on 2026-08-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_dicomimage_dicom_image_patient_f3cea0_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='modality',
            field=models.CharField(choices=[('CT', 'CT'), ('MR', 'MR'), ('CR', 'CR'), ('RF', 'RF'), ('DX', 'DX'), ('MG', 'MG'), ('DR', 'DR'), ('PX', 'PX')], default='', max_length=10, verbose_name='Modality'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='body_part',
            field=models.CharField(choices=[('CT TEMPLATES', 'CT TEMPLATES'), ('MRI TEMPLATES', 'MRI TEMPLATES'), ('X-RAY TEMPLATES', 'X-RAY TEMPLATES')], max_length=100, verbose_name='Body Part'),
        ),
    ]
