# Generated by Django 5.2.5 on 2026-01-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_userprofile_assigned_institutions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_assign_doctors',
            field=models.BooleanField(default=False, help_text='Allow this user to assign doctors to studies'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_templates',
            field=models.BooleanField(default=False, help_text='Allow this user to create and manage report templates'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_images',
            field=models.BooleanField(default=False, help_text='Allow this user to view DICOM images'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_write_reports',
            field=models.BooleanField(default=False, help_text='Allow this user to write and upload reports'),
        ),
    ]
