# Generated by Django 5.2.5 on 2026-08-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_reporttemplate_modality_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dicomimage',
            index=models.Index(fields=['study_date'], name='dicom_image_study_d_dbc703_idx'),
        ),
    ]
